baseurl = "https://squeakycheetah.github.io"
languageCode = "en-us"
theme = "hugo-identity-theme-personal"
title = "Lyssa Dawson"

[params]

	avatar = "lyssa-av.png"
	background = "greenbackground.jpg"

	# Personal settings

  name = "Lyssa Dawson"
	position = "Geeky Rubber Cheetah"

  [[params.social]]
  title = "Twitter"
  icon = "fa-twitter"
  link = "https://www.twitter.com/squeakycheetah"

	[[params.social]]
	title = "Github"
	icon = "fa-github"
	link = "https://github.com/squeakycheetah"

	[[params.social]]
	title = "keybase"
	icon = "fa-key"
	link = "https://keybase.io/squeakycheetah"
