baseurl = "http://squeakycheetah.github.io"
languageCode = "en-us"
theme = "hugo-identity-theme"
title = "Lyssa Dawson"

[params]

	avatar = "lyssa-av.png"

	# Personal settings

  name = "Lyssa Dawson"
	position = "Geeky Rubber Cheetah"

  [[params.social]]
  title = "Twitter"
  icon = "fa-twitter"
  link = "http://www.twitter.com/squeakycheetah"
